spring:
    application:
        name: 'echo'

    datasource:
        name: 'echo'
        url: 'jdbc:postgresql://localhost:5432/echo'
        username: 'nednella'
        password: 'password'

    sql:
        init:
            mode: 'always'

    devtools:
        restart:
            enabled: 'true'
        livereload:
            enabled: 'true'
